Repository Fitness-Mate/Frontend, pull requests merged in 2024-12, with the labels that each got.

#238 [Chore 🚀] husky로 console.log 막기
  .eslintcache
  .gitignore
  .husky/console-log-check.sh
  .husky/pre-commit
  .vscode/settings.json
  package.json
  src/apis/instance.ts
  src/hooks/mutation/usePostAddRoutine.ts
  src/hooks/mutation/usePostRecommend.ts
  src/hooks/mutation/usePostRecommendId.ts
  src/hooks/mutation/usePostSignup.ts
Labels: Minor

#239 [Fix 🪛] 타입관련 빌드오류 수정
  src/components/Button/RoundButton.tsx
  src/store/useModalStore.ts
Labels: HotFix

#207 Feat/#199/mypage
  .prettierrc
  src/assets/icon/circle_separation.svg
  src/assets/icon/handle.svg
  src/assets/icon/pencil_grey.svg
  src/assets/icon/right_arrow_grey.svg
  src/components/Button/RoundButton.tsx
  src/components/EmptyRoutine/EmptyRoutine.tsx
  src/components/EmptyRoutine/StyledEmptyRoutine.ts
  src/components/Icon/Icon.tsx
  src/components/MyWorkout/MyWorkout.stories.tsx
  src/components/MyWorkout/MyWorkout.tsx
  src/components/MyWorkout/StyledMyWorkout.ts
  src/components/Navbar/Navbar.tsx
  src/components/Title/StyledTitle.ts
  src/components/Title/Title.tsx
  src/hooks/query/useGetFetchRecentBodyData.ts
  src/hooks/query/useGetMyRoutines.ts
  src/hooks/query/useGetMyWorkouts.ts
  src/pages/MyPage/My/DragAndDrop.tsx
  src/pages/MyPage/My/MyPage.tsx
  src/pages/MyPage/My/StyledMyPage.ts
  src/routes/Navigator.tsx
  src/styles/theme.ts
  src/types/type.ts
Labels: Feat

#248 Refactor/#247/signup
  src/components/Icon/Icon.tsx
  src/components/Navbar/NavDropDown.tsx
  src/constants/validation.ts
  src/pages/MyPage/Update/UpdateProfile.tsx
  src/pages/Recommend/BodyPart/BodyPart.tsx
  src/pages/Signup/Profile/Profile.tsx
  src/pages/Signup/utils/createSignupList.ts
  src/pages/Signup/utils/getBirthFormat.ts
  src/routes/Navigator.tsx
Labels: Design, Refactor

#252 [Refactoring ⚙️] Pretendard Variable로 변경 및 폰트 크로스 브라우징
  index.html
  package-lock.json
  package.json
  src/assets/fonts/PretendardVariable.woff2
  src/components/Button/RoundButton.tsx
  src/styles/GlobalStyles.tsx
Labels: Refactor

#262 Hotfix/#260/user fetch
  package-lock.json
  package.json
  src/Layout/Mainlayout.tsx
  src/apis/instance.ts
  src/hooks/mutation/useEditProfile.ts
  src/hooks/mutation/useLogin.ts
  src/hooks/mutation/useLogout.ts
  src/hooks/query/useGetUserInfo.ts
  src/hooks/query/useUserInfo.ts
  src/pages/MyPage/Edit/EditPassword.tsx
  src/pages/MyPage/Edit/EditProfile.tsx
  src/pages/MyPage/Routine/MyPage.tsx
  src/pages/Signup/utils/getBirthFormat.ts
  src/store/usePathStore.ts
  src/styles/GlobalStyles.tsx
Labels: HotFix

#270 Ci/#267/GitHub actions
  .eslintcache
  .eslintrc.cjs
  .github/auto_assign.yml
  .github/workflows/auto_assign.yml
  .github/workflows/frontend-ci.yml
  package.json
  src/apis/domain/bodypart.ts
  src/apis/domain/recommend.ts
  src/components/CheckBox/StyledCheckBox.ts
  src/components/Input/components/InputSelect.tsx
  src/components/SpeechBubble/SpeechBubble.stories.tsx
  src/components/Title/Title.stories.tsx
  src/constants/validation.ts
  src/hooks/useDropDown.ts
  src/pages/Signup/BodyFigure/components/Figure/StyledFigure.ts
  src/store/useSignupStore.ts
Labels: CI/CD

#261 Feat/#199/mypage
  .eslintrc.cjs
  package-lock.json
  package.json
  src/apis/domain/myfit.ts
  src/assets/icon/handle.svg
  src/assets/icon/pencil_darkgrey.svg
  src/assets/icon/red_trash.svg
  src/components/DropDown/DropDown.stories.tsx
  src/components/DropDown/DropDown.tsx
  src/components/DropDown/StyledDropDown.ts
  src/components/DropDown/components/MyWorkoutDropDown.tsx
  src/components/DropDown/components/NavDropDown.tsx
  src/components/Icon/Icon.tsx
  src/components/MyWorkout/MyWorkout.stories.tsx
  src/components/Navbar/NavDropDown.tsx
  src/components/Navbar/Navbar.tsx
  src/components/Navbar/StyledNavModal.tsx
  src/components/Title/StyledTitle.ts
  src/hooks/mutation/useDeleteMyWorkout.ts
  src/hooks/mutation/useEditWorkoutList.ts
  src/hooks/query/useGetFetchRecentBodyData.ts
  src/hooks/query/useGetMyWorkouts.ts
  src/hooks/useDropDown.ts
  src/hooks/useTransformBodyData.ts
  src/pages/MyPage/Routine/DragAndDrop.tsx
  src/pages/MyPage/Routine/EmptyRoutine/EmptyRoutine.tsx
  src/pages/MyPage/Routine/EmptyRoutine/StyledEmptyRoutine.ts
  src/pages/MyPage/Routine/MyPage.tsx
  src/pages/MyPage/Routine/MyWorkout/MyWorkout.tsx
  src/pages/MyPage/Routine/MyWorkout/StyledMyWorkout.ts
  src/pages/MyPage/Routine/MyWorkoutItem.tsx
  src/pages/MyPage/Routine/MypageHome.tsx
  src/pages/MyPage/Routine/RoutineTabs.tsx
  src/pages/MyPage/Routine/StyledMyPage.ts
  src/pages/MyPage/Routine/StyledMypageHome.ts
Labels: Design, Feat, Refactor

#274 [Chore 🚀] clone 삭제, fetch-depth 0에서 1로 수정
  .github/workflows/main.yml
Labels: CI/CD

#278 Refactor/#277/unit
  src/components/Accordion/Accordion.stories.tsx
  src/components/Accordion/StyledAccordion.ts
  src/components/Badge/Badge.tsx
  src/components/Bottom/StyledBottom.ts
  src/components/Button/RoundButton.tsx
  src/components/Button/StyledButton.ts
  src/components/Card/StyledCard.ts
  src/components/Card/StyledCardSkeleton.ts
  src/components/CheckBox/ImgCheckBox.tsx
  src/components/CheckBox/StyledCheckBox.ts
  src/components/Chip/Chip.tsx
  src/components/DropDown/StyledDropDown.ts
  src/components/Footer/StyledFooter.ts
  src/components/Input/Input.stories.tsx
  src/components/Input/Input.tsx
  src/components/Input/components/InputInput.tsx
  src/components/Input/components/InputSelect.tsx
  src/components/Input/components/InputText.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/ModalCloseButton.tsx
  src/components/Modal/ModalContent.tsx
  src/components/Modal/ModalFooter.tsx
  src/components/Modal/components/Routine/StyledRoutineModal.tsx
  src/components/Navbar/StyledNavbar.tsx
  src/components/Progressbar/ProgressBar.stories.tsx
  src/components/Progressbar/StyledProgressBar.ts
  src/components/SearchBar/StyledSearchBar.ts
  src/components/SearchField/StyledSearchField.ts
  src/components/SpeechBubble/StyledSpeechBubble.ts
  src/components/Tab/getVariant.ts
  src/components/Title/StyledTitle.ts
  src/pages/Detail/StyledDetail.ts
  src/pages/Home/StyledHome.ts
  src/pages/Login/StyledLogin.ts
  src/pages/MyPage/Edit/EditPassword.tsx
  src/pages/MyPage/Edit/StyledEditProfile.ts
  src/pages/MyPage/Routine/EmptyRoutine/StyledEmptyRoutine.ts
  src/pages/MyPage/Routine/MyWorkout/StyledMyWorkout.ts
  src/pages/MyPage/Routine/StyledMyPage.ts
  src/pages/NotFound/StyledNotFound.ts
  src/pages/Recommend/BodyPart/StyledBodyPart.ts
  src/pages/Recommend/Machine/StyledMachine.ts
  src/pages/Recommend/Result/StyledResult.ts
  src/pages/Recommend/StyledRecommend.ts
  src/pages/Search/DropdownForm.tsx
  src/pages/Search/StyledSearch.ts
  src/pages/Signup/BodyFigure/BodyFigure.tsx
  src/pages/Signup/BodyFigure/components/Figure/StyledFigure.ts
  src/pages/Signup/BodyFigure/components/Ratio/StyledRatio.ts
  src/pages/Signup/Complete/StyledComplete.ts
  src/pages/Signup/StyledSignup.ts
  src/stories/icon.mdx
  src/stories/intro.mdx
  src/styles/GlobalStyles.tsx
  src/styles/theme.ts
  src/utils/getScrollAnimaion.ts
Labels: Refactor
